"use client";
import '../styles/globals.scss'
import Sidebar from '../components/Sidebar'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="App">
      <Sidebar />
      <div className="page">
      <main>{children}</main>
      </div>
    </div>
  )
}


