import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "./_components/header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <div className="flex max-h-1 max-w-full flex-col">
          {/*  <div className="flex-none">
            <div className=" header sticky top-0 flex flex-row items-center justify-center space-x-5 bg-gradient-to-r from-gray-800 to-gray-900">
              <Header />
            </div>
          </div> */}
          <div className=" flex-1">
            <main
              className="from-lightBlue to-darkBlue
               min-h-[calc(100vh-48px)]  bg-gradient-to-b bg-center text-white"
            >
              <TRPCReactProvider cookies={cookies().toString()}>
                {children}
              </TRPCReactProvider>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
